"""
Summary model.

One summary per meeting (enforced by UNIQUE constraint on meeting_id).
Contains the overview text generated by AI or seeded for the demo.
"""

from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.database import Base


class Summary(Base):
    __tablename__ = "summaries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # One summary per meeting — enforced by UNIQUE at both ORM and DB level.
    meeting_id: Mapped[int] = mapped_column(
        ForeignKey("meetings.id", ondelete="CASCADE"), nullable=False, unique=True
    )

    # 2–4 paragraph overview of the meeting.
    overview: Mapped[str] = mapped_column(Text, nullable=False)

    # Which system produced this summary: "seed" | "llm" | "manual"
    generated_by: Mapped[str] = mapped_column(String(50), nullable=False, default="seed")
    generated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )

    meeting: Mapped["Meeting"] = relationship("Meeting", back_populates="summary")


from app.models.meeting import Meeting  # noqa: E402
